/* Editorial Terminal: core lessons are practical field notes, not encyclopedic reference pages. */
export type CoreDeepDive = { mentalModel: string; when: string; tradeoff: string; checklist: string[]; exercise: string };

const d = (mentalModel: string, when: string, tradeoff: string, checklist: string[], exercise: string): CoreDeepDive => ({ mentalModel, when, tradeoff, checklist, exercise });

export const coreDeepDives: Record<string, CoreDeepDive> = {
  "First Principles Thinking": d("Pecah masalah sampai asumsi paling dasar, lalu bangun solusi dari sana.", "Saat requirement terasa kabur atau solusi lama diteruskan tanpa alasan.", "Lebih lambat di awal, tetapi mengurangi keputusan yang diwariskan secara buta.", ["Tulis outcome yang ingin dicapai", "Pisahkan fakta dari asumsi", "Uji constraint yang benar-benar nyata"], "Ambil satu fitur di project-mu. Tulis ulang masalahnya tanpa menyebut framework atau implementasi."),
  "Systems Thinking": d("Sebuah fitur adalah bagian dari sistem: user, service, data, operasi, dan insentif saling memengaruhi.", "Saat perubahan lokal memunculkan efek samping di tempat lain.", "Model mental lebih luas membutuhkan waktu, tetapi mencegah optimasi satu komponen yang merusak alur keseluruhan.", ["Gambar input dan output", "Cari feedback loop", "Tentukan siapa yang terdampak"], "Petakan satu request dari UI sampai database dan tulis dua efek samping yang mungkin muncul."),
  "Second Order Thinking": d("Jangan berhenti di dampak langsung; tanyakan apa yang terjadi setelah dampak itu.", "Saat keputusan terlihat bagus sekarang tetapi berpotensi menciptakan biaya lanjutan.", "Analisis lebih dalam memperlambat eksekusi, namun membuat konsekuensi tersembunyi terlihat.", ["Tulis efek pertama", "Tanya 'lalu apa?' dua kali", "Bandingkan horizon waktu"], "Evaluasi keputusan menambah cache: apa efeknya pada freshness, invalidation, dan debugging?"),
  "Trade-off Thinking": d("Tidak ada solusi gratis; setiap pilihan menukar latency, biaya, kompleksitas, atau reliability.", "Saat tim berdebat mencari solusi yang 'paling benar'.", "Membuat trade-off eksplisit mengurangi dogma, tetapi kadang keputusan tetap harus dibuat dengan data terbatas.", ["Sebutkan tujuan utama", "Tulis apa yang dikorbankan", "Tentukan sinyal untuk meninjau ulang"], "Bandingkan monolith dan microservices untuk product kecil dengan tim tiga orang."),
  "KISS (Keep It Simple, Stupid)": d("Solusi sederhana bukan solusi dangkal; ia mengurangi jumlah bagian yang bisa gagal.", "Saat desain mulai memiliki abstraction, konfigurasi, dan layer yang belum dibutuhkan.", "Kesederhanaan hari ini bisa membatasi besok jika constraint masa depan sudah jelas.", ["Hapus layer yang tidak memberi nilai", "Pilih default yang masuk akal", "Uji apakah user benar-benar butuh fleksibilitas"], "Refactor satu fungsi kompleks menjadi alur yang bisa dijelaskan dalam tiga kalimat."),
  "YAGNI (You Aren't Gonna Need It)": d("Jangan membayar kompleksitas untuk kebutuhan yang belum terbukti.", "Saat ingin membangun extension point atau konfigurasi 'untuk nanti'.", "Menunda fleksibilitas dapat membuat migrasi masa depan lebih mahal, jadi gunakan evidence untuk menilai risiko.", ["Cari kebutuhan aktual", "Tentukan trigger untuk menambah fleksibilitas", "Hindari API publik prematur"], "Temukan satu abstraction di codebase yang hanya punya satu caller. Apakah harus dipertahankan?"),
  "Separation of Concerns": d("Pisahkan alasan perubahan yang berbeda agar satu perubahan tidak memaksa banyak bagian ikut berubah.", "Saat business rule, transport, persistence, dan UI tercampur.", "Boundary menambah sedikit boilerplate, tetapi membuat testing dan perubahan lebih terlokalisasi.", ["Kelompokkan alasan perubahan", "Definisikan interface antar concern", "Cek apakah boundary bisa diuji terpisah"], "Pisahkan handler HTTP dari business decision pada satu endpoint di project-mu."),
  "High Cohesion, Low Coupling": d("Kode yang sering berubah bersama sebaiknya tinggal berdekatan; bagian yang jarang berubah bersama sebaiknya tidak saling mengikat.", "Saat perubahan kecil memerlukan edit lintas banyak module.", "Coupling rendah bisa menambah indirection, tetapi menurunkan blast radius perubahan.", ["Cari perubahan yang selalu berpasangan", "Kurangi knowledge lintas module", "Ukur biaya koordinasi"], "Ambil satu folder yang sering disentuh. Tandai dependency yang sebenarnya hanya kebetulan."),
  "Single Responsibility Principle (SRP)": d("Satu module sebaiknya memiliki satu alasan utama untuk berubah.", "Saat class atau function menangani validasi, side effect, formatting, dan persistence sekaligus.", "Memecah terlalu agresif menciptakan file kecil tanpa cohesion, jadi fokus pada alasan perubahan.", ["Identifikasi actor yang memicu perubahan", "Pisahkan side effect", "Jaga interface tetap kecil"], "Cari satu function panjang dan tulis tiga alasan berbeda yang bisa membuatnya berubah."),
  "Composition over Inheritance": d("Rakit behavior dari komponen kecil daripada membangun hierarki yang sulit diubah.", "Saat subclass mulai override banyak method atau inheritance dipakai hanya untuk reuse.", "Composition memberi fleksibilitas, tetapi wiring dependency harus dirancang dengan jelas.", ["Identifikasi behavior yang bisa dipisah", "Inject dependency", "Hindari shared mutable state"], "Ganti satu inheritance chain dengan dua object yang dikomposisikan."),
  "Leaky Abstractions": d("Abstraction bocor ketika detail yang ingin disembunyikan muncul kembali lewat error, latency, atau edge case.", "Saat API terlihat sederhana tetapi caller harus memahami storage, network, atau consistency.", "Abstraction yang lebih jujur mungkin lebih verbose, tetapi mengurangi surprise saat failure.", ["Dokumentasikan failure mode", "Expose constraint penting", "Jangan sembunyikan latency sebagai synchronous magic"], "Cari abstraction yang membuat caller menebak-nebak mengapa hasil bisa stale atau timeout."),
  "Domain-Oriented Microservice Architecture": d("Service boundary mengikuti domain dan ownership, bukan sekadar tabel atau layer teknis.", "Saat organisasi dan domain cukup besar untuk membutuhkan autonomy.", "Autonomy dibayar dengan network call, observability, deployment, dan consistency yang lebih sulit.", ["Definisikan domain ownership", "Minimalkan shared database", "Ukur biaya koordinasi"], "Ambil fitur checkout dan pecah berdasarkan capability, bukan berdasarkan CRUD table."),
  "Monolith vs Microservices": d("Pilih unit deployment berdasarkan ukuran domain, tim, dan kebutuhan scaling, bukan tren.", "Saat tim menilai apakah sistem perlu dipisah.", "Monolith murah untuk dipahami; microservices memberi isolation tetapi menambah distributed-systems cost.", ["Nilai team size", "Cari kebutuhan independent deploy", "Hitung operational overhead"], "Buat decision note untuk tetap monolith selama 12 bulan berikutnya."),
  "Event-Driven Architecture": d("Producer menerbitkan fakta; consumer bereaksi secara asynchronous.", "Saat workflow perlu decoupling atau banyak consumer berbeda.", "Decoupling dibayar dengan eventual consistency, duplicate event, ordering, dan debugging lintas waktu.", ["Definisikan event sebagai fakta", "Siapkan idempotency", "Tetapkan ownership schema"], "Desain event setelah pembayaran berhasil dan sebutkan dua consumer yang aman retry."),
  "CQRS (Command Query Responsibility Segregation)": d("Model untuk menulis command tidak harus sama dengan model untuk membaca query.", "Saat read shape dan write invariant memiliki kebutuhan yang sangat berbeda.", "Read model bisa cepat dan spesifik, tetapi sinkronisasi dan kompleksitas operasional meningkat.", ["Pisahkan intent command", "Tentukan source of truth", "Rancang rebuild read model"], "Tentukan apakah halaman dashboard-mu benar-benar membutuhkan read model terpisah."),
  "Domain-Driven Design (DDD)": d("Gunakan bahasa domain dan boundary bisnis untuk membentuk model software.", "Saat domain memiliki aturan dan istilah yang kompleks.", "Model domain yang baik mengurangi miskomunikasi, tetapi membutuhkan kolaborasi intens dengan domain expert.", ["Temukan ubiquitous language", "Identifikasi aggregate dan invariant", "Tentukan bounded context"], "Interview user internal dan buat glossary 10 istilah yang harus konsisten di codebase."),
  "Bounded Context": d("Istilah yang sama bisa memiliki arti berbeda di boundary domain yang berbeda.", "Saat satu model global mulai penuh pengecualian.", "Boundary menghindari model raksasa, tetapi translasi antar context harus dirawat.", ["Tulis definisi lokal", "Tentukan context map", "Hindari shared model tanpa ownership"], "Bandingkan arti 'user' di billing, support, dan identity."),
  "Bottleneck Theory": d("Throughput sistem dibatasi constraint paling sempit, bukan rata-rata semua komponennya.", "Saat optimasi dilakukan di banyak tempat tetapi throughput tidak naik.", "Fokus pada bottleneck memberi leverage tinggi, tetapi bottleneck dapat berpindah setelah diperbaiki.", ["Ukur flow end-to-end", "Cari constraint aktif", "Re-measure setelah intervensi"], "Gambar alur request dan tandai satu resource yang paling mungkin membatasi throughput."),
  "Amdahl's Law": d("Speedup total dibatasi bagian sistem yang tidak bisa diparalelkan.", "Saat tim berharap scaling satu komponen akan mempercepat keseluruhan.", "Investasi parallelism cepat sia-sia jika serial portion masih dominan.", ["Pisahkan serial dan parallel work", "Ukur baseline", "Hitung ceiling improvement"], "Ambil pipeline build atau request flow dan cari bagian serial yang membatasi improvement."),
  "Horizontal Scaling": d("Tambah instance untuk membagi beban, dengan syarat state dan koordinasi dapat didistribusikan.", "Saat satu mesin tidak lagi cukup atau availability membutuhkan redundancy.", "Kapasitas meningkat, tetapi load balancing, shared state, dan consistency ikut menjadi masalah.", ["Buat service stateless bila mungkin", "Rancang partitioning", "Uji scale-out behavior"], "Sebutkan state apa yang harus dipindahkan dari memory instance sebelum scale-out."),
  "Load Shedding": d("Saat overload, tolak sebagian pekerjaan secara sadar agar core service tetap hidup.", "Saat demand melebihi kapasitas dan semua request tidak bisa dilayani.", "Sebagian user atau fitur dikorbankan, tetapi sistem tidak jatuh total.", ["Tentukan request prioritas", "Kirim response yang jujur", "Monitor shed rate"], "Pilih endpoint yang boleh mengembalikan 429 ketika dependency mulai overload."),
  "Backpressure": d("Producer harus melambat ketika consumer tidak mampu mengejar.", "Saat queue tumbuh dan latency memburuk karena upstream terus mengirim.", "Menjaga sistem stabil dapat meningkatkan latency atau menolak pekerjaan lebih awal.", ["Tetapkan queue limit", "Propagate pressure", "Bedakan retryable dan non-retryable work"], "Gambar aliran upload atau job queue dan tentukan titik backpressure-nya."),
  "Eventual Consistency": d("Replica atau read model dapat sementara berbeda, tetapi menuju convergence.", "Saat availability dan latency lebih penting daripada read-after-write global.", "User experience harus menghadapi stale read dan conflict resolution.", ["Definisikan freshness window", "Tentukan conflict policy", "Berikan status yang jujur ke user"], "Desain UI setelah user mengubah profile sementara search index belum ter-update."),
  "CAP Theorem": d("Dalam partition network, sistem terdistribusi harus memilih prioritas consistency atau availability.", "Saat memilih behavior ketika node tidak bisa saling berkomunikasi.", "CAP bukan label sederhana untuk database; keputusan bergantung pada operation dan failure mode.", ["Tentukan partition behavior", "Pisahkan consistency requirement per operation", "Dokumentasikan degraded mode"], "Pilih behavior untuk read saldo saat service ledger tidak bisa dijangkau."),
  "Idempotency": d("Mengulang request yang sama tidak menciptakan efek bisnis tambahan.", "Saat network retry, duplicate delivery, atau user double-click mungkin terjadi.", "Menyimpan idempotency key dan result membutuhkan storage serta policy expiry.", ["Definisikan operation identity", "Simpan outcome atau dedupe record", "Tentukan TTL dan conflict behavior"], "Tambahkan idempotency design untuk endpoint charge atau create order."),
  "Fault Tolerance": d("Sistem tetap menyediakan behavior yang dapat diterima ketika komponen gagal.", "Saat dependency, node, atau network failure adalah hal yang pasti akan terjadi.", "Redundancy dan fallback menambah biaya, tetapi mengurangi blast radius.", ["List failure modes", "Tentukan fallback", "Uji recovery path"], "Tulis behavior saat payment provider timeout selama 30 detik."),
  "Circuit Breaker": d("Setelah failure berulang, hentikan call sementara agar dependency dan caller bisa pulih.", "Saat dependency lambat atau error dan retry mulai memperparah beban.", "Open circuit bisa menolak request sehat jika threshold buruk, jadi perlu observability dan tuning.", ["Tentukan error threshold", "Sediakan half-open probe", "Definisikan fallback"], "Pilih threshold circuit breaker untuk dependency recommendation yang non-critical."),
  "Retry Storm": d("Retry tanpa koordinasi mengubah satu failure menjadi lonjakan traffic baru.", "Saat client, queue, dan service sama-sama melakukan retry.", "Retry membantu transient failure, tetapi harus dibatasi, diberi jitter, dan dihentikan di boundary yang tepat.", ["Batasi attempts", "Gunakan exponential backoff + jitter", "Jangan retry non-idempotent tanpa guard"], "Audit semua layer retry pada satu request dan hitung worst-case amplification."),
  "Testing Pyramid": d("Test murah dan cepat sebaiknya mendominasi; test integration dan end-to-end dipakai untuk confidence yang tidak bisa dicapai unit test.", "Saat suite lambat, flaky, atau terlalu bergantung pada UI.", "Unit test cepat tetapi bisa memberi false confidence jika contract antar komponen tidak diuji.", ["Test behavior penting", "Jaga integration test terarah", "Pantau flaky rate dan runtime"], "Ambil satu fitur dan bagi test-nya menjadi unit, integration, dan satu happy-path end-to-end."),
  "Technical Debt": d("Shortcut hari ini adalah kewajiban masa depan dengan bunga berupa lambatnya perubahan dan naiknya risiko.", "Saat memilih solusi cepat karena deadline atau informasi belum lengkap.", "Tidak semua debt harus dibayar segera; bayar yang menghambat flow atau memperbesar risiko.", ["Catat alasan debt", "Estimasi bunga", "Pasang trigger repayment"], "Tulis satu debt di project-mu, siapa yang terdampak, dan sinyal kapan harus dilunasi."),
};
