/* Editorial Terminal: runnable labs stay dependency-free so a new engineer can copy, run, and inspect the result. */
export type RunnableExample = { language: string; command: string; code: string; output: string };

export const runnableExamples: Record<string, RunnableExample> = {
  "Big O sebagai Trade-off Praktis (bukan sekadar teori)": { language: "JavaScript", command: "node big-o.js", code: `const ids = new Set(["a-1", "a-2", "a-3"]);\nconst requested = ["a-2", "a-9"];\n\n// Set.has is approximately O(1) per lookup.\nconst found = requested.filter((id) => ids.has(id));\nconsole.log(found);`, output: `[ 'a-2' ]` },
  "Caching Strategies (cache invalidation, cache stampede, cache aside)": { language: "JavaScript", command: "node cache-aside.js", code: `const cache = new Map();\nconst database = new Map([["user:1", { name: "Mira" }]]);\n\nasync function getUser(id) {\n  const key = \`user:\${id}\`;\n  if (cache.has(key)) return { source: "cache", value: cache.get(key) };\n  const value = database.get(key);\n  cache.set(key, value);\n  return { source: "database", value };\n}\n\nconsole.log(await getUser(1));\nconsole.log(await getUser(1));`, output: `{ source: 'database', value: { name: 'Mira' } }\n{ source: 'cache', value: { name: 'Mira' } }` },
  "Idempotency": { language: "JavaScript", command: "node idempotency.js", code: `const processed = new Map();\n\nfunction createPayment(key, amount) {\n  if (processed.has(key)) return processed.get(key);\n  const result = { id: \"pay-001\", amount, status: \"accepted\" };\n  processed.set(key, result);\n  return result;\n}\n\nconsole.log(createPayment(\"checkout-42\", 120));\nconsole.log(createPayment(\"checkout-42\", 120));`, output: `The same idempotency key returns the same payment.` },
  "Retry Storm": { language: "JavaScript", command: "node retry.js", code: `const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));\n\nasync function withRetry(work, attempts = 3) {\n  for (let attempt = 1; attempt <= attempts; attempt++) {\n    try { return await work(); }\n    catch (error) {\n      if (attempt === attempts) throw error;\n      const jitter = Math.floor(Math.random() * 20);\n      await sleep(2 ** attempt * 50 + jitter);\n    }\n  }\n}\n\nlet calls = 0;\nconst result = await withRetry(async () => {\n  calls++;\n  if (calls < 3) throw new Error(\"temporary failure\");\n  return \"ok\";\n});\nconsole.log({ result, calls });`, output: `{ result: 'ok', calls: 3 }` },
  "Circuit Breaker": { language: "JavaScript", command: "node circuit-breaker.js", code: `let failures = 0;\nlet state = \"closed\";\n\nfunction callDependency() {\n  if (state === \"open\") return \"fallback\";\n  try {\n    failures++;\n    if (failures <= 2) throw new Error(\"timeout\");\n    state = \"closed\";\n    return \"live response\";\n  } catch {\n    if (failures >= 2) state = \"open\";\n    return \"fallback\";\n  }\n}\n\nconsole.log(callDependency());\nconsole.log(callDependency());\nconsole.log({ state });`, output: `fallback\nfallback\n{ state: 'open' }` },
  "Event-Driven Architecture": { language: "JavaScript", command: "node events.js", code: `const handlers = new Map();\nconst on = (event, handler) => handlers.set(event, handler);\nconst publish = (event, payload) => handlers.get(event)?.(payload);\n\non(\"OrderPaid\", ({ orderId }) => {\n  console.log(\`send receipt for \${orderId}\`);\n});\n\npublish(\"OrderPaid\", { orderId: \"order-7\" });`, output: `send receipt for order-7` },
  "Backpressure": { language: "JavaScript", command: "node backpressure.js", code: `const queue = [];\nconst MAX_QUEUE = 2;\n\nfunction accept(job) {\n  if (queue.length >= MAX_QUEUE) return { accepted: false, reason: \"backpressure\" };\n  queue.push(job);\n  return { accepted: true, depth: queue.length };\n}\n\nconsole.log(accept(\"job-1\"));\nconsole.log(accept(\"job-2\"));\nconsole.log(accept(\"job-3\"));`, output: `The third job is rejected before the queue grows without bound.` },
  "Testing Pyramid": { language: "JavaScript", command: "node --test pricing.test.js", code: `import test from \"node:test\";\nimport assert from \"node:assert/strict\";\n\nfunction total(price, quantity) {\n  if (quantity < 1) throw new Error(\"quantity must be positive\");\n  return price * quantity;\n}\n\ntest(\"calculates a line total\", () => {\n  assert.equal(total(12, 3), 36);\n});\n\ntest(\"rejects invalid quantity\", () => {\n  assert.throws(() => total(12, 0), /positive/);\n});`, output: `2 tests passed` },
};
