/* Editorial Terminal: TypeScript variants make types visible without adding runtime setup. */
export const runnableTypeScript: Record<string, string> = {
  "Big O sebagai Trade-off Praktis (bukan sekadar teori)": `const ids: Set<string> = new Set(["a-1", "a-2", "a-3"]);\nconst requested: string[] = ["a-2", "a-9"];\nconst found: string[] = requested.filter((id: string) => ids.has(id));\nconsole.log(found);`,
  "Caching Strategies (cache invalidation, cache stampede, cache aside)": `type User = { name: string };\nconst cache: Map<string, User | undefined> = new Map();\nconst database: Map<string, User> = new Map([["user:1", { name: "Mira" }]]);\n\nasync function getUser(id: number): Promise<{ source: string; value: User | undefined }> {\n  const key = \`user:\${id}\`;\n  if (cache.has(key)) return { source: "cache", value: cache.get(key) };\n  const value = database.get(key);\n  cache.set(key, value);\n  return { source: "database", value };\n}\n\nconsole.log(await getUser(1));\nconsole.log(await getUser(1));`,
  "Idempotency": `type Payment = { id: string; amount: number; status: string };\nconst processed: Map<string, Payment> = new Map();\n\nfunction createPayment(key: string, amount: number): Payment {\n  if (processed.has(key)) return processed.get(key)!;\n  const result: Payment = { id: "pay-001", amount, status: "accepted" };\n  processed.set(key, result);\n  return result;\n}\n\nconsole.log(createPayment("checkout-42", 120));\nconsole.log(createPayment("checkout-42", 120));`,
  "Retry Storm": `const sleep = (ms: number): Promise<void> => new Promise((resolve) => setTimeout(resolve, ms));\n\nasync function withRetry<T>(work: () => Promise<T>, attempts = 3): Promise<T> {\n  for (let attempt = 1; attempt <= attempts; attempt++) {\n    try { return await work(); }\n    catch (error) {\n      if (attempt === attempts) throw error;\n      const jitter = Math.floor(Math.random() * 20);\n      await sleep(2 ** attempt * 50 + jitter);\n    }\n  }\n  throw new Error("unreachable");\n}\n\nlet calls = 0;\nconst result = await withRetry(async () => {\n  calls++;\n  if (calls < 3) throw new Error("temporary failure");\n  return "ok";\n});\nconsole.log({ result, calls });`,
  "Circuit Breaker": `let failures: number = 0;\nlet state: "closed" | "open" = "closed";\n\nfunction callDependency(): string {\n  if (state === "open") return "fallback";\n  try {\n    failures++;\n    if (failures <= 2) throw new Error("timeout");\n    state = "closed";\n    return "live response";\n  } catch {\n    if (failures >= 2) state = "open";\n    return "fallback";\n  }\n}\n\nconsole.log(callDependency());\nconsole.log(callDependency());\nconsole.log({ state });`,
  "Event-Driven Architecture": `type OrderPaid = { orderId: string };\ntype Handler = (event: OrderPaid) => void;\nconst handlers: Map<string, Handler> = new Map();\nconst on = (event: string, handler: Handler): void => handlers.set(event, handler);\nconst publish = (event: string, payload: OrderPaid): void => handlers.get(event)?.(payload);\n\non("OrderPaid", ({ orderId }: OrderPaid) => {\n  console.log(\`send receipt for \${orderId}\`);\n});\n\npublish("OrderPaid", { orderId: "order-7" });`,
  "Backpressure": `const queue: string[] = [];\nconst MAX_QUEUE: number = 2;\n\nfunction accept(job: string): { accepted: boolean; depth?: number; reason?: string } {\n  if (queue.length >= MAX_QUEUE) return { accepted: false, reason: "backpressure" };\n  queue.push(job);\n  return { accepted: true, depth: queue.length };\n}\n\nconsole.log(accept("job-1"));\nconsole.log(accept("job-2"));\nconsole.log(accept("job-3"));`,
  "Testing Pyramid": `import test from "node:test";\nimport assert from "node:assert/strict";\n\nfunction total(price: number, quantity: number): number {\n  if (quantity < 1) throw new Error("quantity must be positive");\n  return price * quantity;\n}\n\ntest("calculates a line total", () => {\n  assert.equal(total(12, 3), 36);\n});\n\ntest("rejects invalid quantity", () => {\n  assert.throws(() => total(12, 0), /positive/);\n});`,
};
