from pathlib import Path
p = Path('/home/ubuntu/missing-curriculum/client/src/pages/Home.tsx')
s = p.read_text()
s = s.replace('  const [activeChapter, setActiveChapter] = useState("All");', '  const [activeChapter, setActiveChapter] = useState("All");\n  const [activeLevel, setActiveLevel] = useState("All");\n  const [quizAnswer, setQuizAnswer] = useState<number | null>(null);')
s = s.replace('    const matchesChapter = activeChapter === "All" || item.chapter.startsWith(activeChapter);\n    const matchesQuery = `${item.title} ${item.kicker} ${item.description}`.toLowerCase().includes(query.toLowerCase());\n    return matchesChapter && matchesQuery;', '    const matchesChapter = activeChapter === "All" || item.chapter.startsWith(activeChapter);\n    const matchesLevel = activeLevel === "All" || item.level === activeLevel;\n    const matchesQuery = `${item.title} ${item.kicker} ${item.description} ${item.caseTitle} ${item.caseContext}`.toLowerCase().includes(query.toLowerCase());\n    return matchesChapter && matchesLevel && matchesQuery;')
s = s.replace('  }), [activeChapter, query]);', '  }), [activeChapter, activeLevel, query]);')
s = s.replace('setActiveChapter(chapter.id); document.getElementById("index")?.scrollIntoView', 'setActiveChapter(chapter.id); setActiveLevel("All"); document.getElementById("index")?.scrollIntoView')
s = s.replace('className="mt-10 text-left" onClick={() => setSelected(concept)}', 'className="mt-10 text-left" onClick={() => { setSelected(concept); setQuizAnswer(null); }}')
s = s.replace('<div className="mb-8 flex flex-wrap gap-2">{["All", ...chapters.map(c => c.id)].map((id) => <button', '<div className="mb-8 flex flex-wrap gap-2"><span className="filter-group-label">Topic</span>{["All", ...chapters.map(c => c.id)].map((id) => <button')
s = s.replace('</button>)}</div>\n          <div className="grid gap-4', '</button>)}<span className="filter-group-label ml-3">Level</span>{["All", "Foundation", "Working knowledge", "Advanced"].map((id) => <button key={id} onClick={() => setActiveLevel(id)} className={`filter-chip ${activeLevel === id ? "active" : ""}`}>{id === "All" ? "All levels" : id}</button>)}</div>\n          <div className="grid gap-4')
s = s.replace('<p className="mt-8 max-w-xl text-[17px] leading-7">{selected.description}</p>', '<p className="mt-8 max-w-xl text-[17px] leading-7">{selected.description}</p><div className="quiz-panel mt-8"><div className="flex items-center justify-between gap-4"><span className="section-label">What would you do?</span><span className="font-mono text-[10px] uppercase tracking-wider text-graphite">Decision drill</span></div><p className="mt-4 font-display text-2xl leading-tight">{selected.quiz.prompt}</p><div className="mt-5 grid gap-2">{selected.quiz.options.map((option, optionIndex) => <button key={option} onClick={() => setQuizAnswer(optionIndex)} className={`quiz-option ${quizAnswer === optionIndex ? (optionIndex === selected.quiz.answer ? "correct" : "wrong") : ""}`}><span className="quiz-letter">{String.fromCharCode(65 + optionIndex)}</span><span>{option}</span>{quizAnswer === optionIndex && <span className="ml-auto font-mono text-[9px] uppercase">{optionIndex === selected.quiz.answer ? "Correct" : "Try again"}</span>}</button>)}</div>{quizAnswer !== null && <div className={`quiz-feedback ${quizAnswer === selected.quiz.answer ? "correct" : "wrong"}`}><strong>{quizAnswer === selected.quiz.answer ? "Good call." : "Not quite."}</strong> {selected.quiz.explanation}</div>}</div>')
s = s.replace('<div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="callout">', '<div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="callout">')
# insert technical block before the existing try-this callouts
needle = '<div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="callout">'
tech = '{selected.technical && <div className="technical-panel mt-5"><div className="flex items-center justify-between"><span className="section-label">{selected.technical.label}</span><span className="font-mono text-[10px] text-graphite">{selected.technical.kind === "code" ? "diff" : "flow"}</span></div>{selected.technical.kind === "code" ? <div className="code-diff mt-4"><div className="diff-line removed">− {selected.technical.before}</div><div className="diff-line added">+ {selected.technical.after}</div></div> : <div className="diagram-flow mt-5">{selected.technical.nodes?.map((node, nodeIndex) => <span key={node}>{node}{nodeIndex < (selected.technical.nodes?.length || 0) - 1 && <b>→</b>}</span>)}</div>}</div>}'
s = s.replace(needle, tech + needle, 1)
p.write_text(s)
print('added search filters, decision quiz, and technical examples UI')
