/* Editorial Terminal: the graph turns the curriculum into a visible field map, not a black-box sequence. */
import { useMemo, useState } from "react";
import { ArrowUpRight } from "lucide-react";
import { graphEdges, graphNodes } from "@/lib/learningData";

export default function PrerequisiteGraph({ understood }: { understood: number[] }) {
  const [selected, setSelected] = useState(graphNodes[0].id);
  const active = graphNodes.find((node) => node.id === selected) || graphNodes[0];
  const connected = useMemo(() => new Set(graphEdges.filter((edge) => edge.from === selected || edge.to === selected).flatMap((edge) => [edge.from, edge.to])), [selected]);
  return <section id="graph" className="border-y border-ink/10 bg-ink text-paper"><div className="mx-auto max-w-[1440px] px-5 py-20 lg:px-16 lg:py-24"><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="section-label text-signal">04 / Prerequisite graph</p><h2 className="mt-5 max-w-xl font-display text-5xl leading-[.95] tracking-[-.04em]">Lihat <em className="text-signal">urutan dependencynya.</em></h2><p className="mt-6 max-w-md text-[15px] leading-7 text-paper/65">Klik node untuk melihat konsep yang perlu dipahami sebelum melangkah. Garis bukan dogma—ia adalah peta awal untuk mengurangi lompatan yang terlalu jauh.</p><div className="mt-8 border-l border-signal pl-4"><p className="font-mono text-[10px] uppercase tracking-wider text-signal">Selected node</p><h3 className="mt-2 font-display text-3xl">{active.label}</h3><p className="mt-3 text-sm leading-6 text-paper/65">{understood.includes(active.id) ? "Sudah ditandai understood. Pilih node berikutnya untuk memperluas peta." : "Belum ditandai understood. Buka konsep ini, lakukan case dan quiz, lalu tandai selesai."}</p><a href={`/#concept-${active.id}`} className="mt-5 inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-wider text-signal underline underline-offset-4">Open concept <ArrowUpRight size={13}/></a></div></div><div><div className="graph-canvas"><svg viewBox="0 0 700 220" role="img" aria-label="Prerequisite relationships between foundational concepts" className="h-auto w-full">{graphEdges.map((edge) => { const from=graphNodes.find((node)=>node.id===edge.from)!; const to=graphNodes.find((node)=>node.id===edge.to)!; const isActive=connected.has(edge.from)&&connected.has(edge.to); return <line key={`${edge.from}-${edge.to}`} x1={from.x+54} y1={from.y+15} x2={to.x} y2={to.y+15} className={isActive ? "graph-edge active" : "graph-edge"}/>; })}</svg>{graphNodes.map((node) => <button key={node.id} onClick={() => setSelected(node.id)} className={`graph-node ${selected===node.id ? "selected" : ""} ${connected.has(node.id) ? "connected" : ""}`} style={{ left: `${(node.x/700)*100}%`, top: `${(node.y/220)*100}%` }}><span className="graph-dot">{understood.includes(node.id) ? "✓" : node.id}</span><span>{node.label}</span></button>)}</div><div className="mt-5 flex flex-wrap gap-3 font-mono text-[9px] uppercase tracking-wider text-paper/55"><span><i className="legend-dot foundation"/> foundation</span><span><i className="legend-dot working"/> working knowledge</span><span><i className="legend-dot senior"/> senior</span></div></div></div></div></section>;
}
